# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5aac800873cbbb1023522801cef8af98493660c3c761c0781ff87150738ea0e613262cd58f728bc1423e638fd975e1f8123db66015482ea18204de026ade857

test:
  secret_key_base: a1cf444ce20e467bec69da872163a32ad9b68551b3b0b1536267bc296b71563baffcc5dec2d23475407e7073801c6b428bd2fcf4d7d89ff4c42a5e4ff6c085a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
